# Generated by Django 5.1.1 on 2024-09-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('paddr', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_score', models.IntegerField(blank=True, null=True)),
                ('q2_score', models.IntegerField(blank=True, null=True)),
                ('q3_score', models.IntegerField(blank=True, null=True)),
                ('q4_score', models.IntegerField(blank=True, null=True)),
                ('q5_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pword', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('pname', models.OneToOneField(db_column='pname', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pharmacyapp.pharmacy')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('uptime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
